### ISSUE TITLE
Not Working in 1.14.3

### ISSUE THREAD

**Issue by Jay9519** [kaboomserver/commandspy#1] opened 2019-06-29 23:10 UTC
Using Spigot 1.14.3

[23:25:01] [Server thread/INFO]: Jay9519 issued server command: /commandspy
[23:25:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'commandspy' in plugin CommandSpy v2.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot-latest.jar:git-Spigot-595711b-c699792]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-latest.jar:git-Spigot-595711b-c699792]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Cannot translate null text
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
at com.juno.commandspy.Main.onCommand(Main.java:79) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-latest.jar:git-Spigot-595711b-c699792]
... 17 more

**Comment by mathiascode** [comment] 2019-06-30 00:00
I tried the plugin again in Spigot 1.14.3 instead of Paper 1.14.3, but I still can't reproduce the issue. It's a fresh server with CommandSpy as the only loaded plugin.

I suggest grabbing a new copy of this repo and compiling it again, or testing this jar: https://github.com/kaboomserver/base-files/raw/master/plugins/CommandSpy.jar

**Comment by mathiascode** [comment] 2019-06-30 00:04
Oh, seems like you're using this plugin: https://www.spigotmc.org/resources/commandspy.18498/

I'm not the author of that CommandSpy plugin, so I can't help you with that.

**Comment by Jay9519** [comment] 2019-06-30 05:05
oh, I didn't realize there were multiple plugins with the same name, if yours works, I'll switch over

**Comment by Jay9519** [comment] 2019-06-30 05:52
any permissions for it?

**Comment by mathiascode** [comment] 2019-06-30 10:03
There's one permission for the /commandspy command, commandspy.command.

If you decide to use this plugin, keep in mind that I created it for my own Minecraft server, with no intention of keeping things stable for other servers. Things may break or change in the future.

**Comment by Jay9519** [comment] 2019-06-30 11:09
I understand mate, if you wish for me to not use it i'm more then happy to not use it

**Comment by mathiascode** [comment] 2019-06-30 11:43
It's up to you. Feel free to use it, but don't expect support. The code is released into the public domain.

**Closed as completed by mathiascode** 2019-06-30 11:43 UTC

**Comment by Jay9519** [comment] 2019-06-30 14:12
Just let you know it works great with lots of plugins installed
